kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-priv
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system
- developer
groups:
- my-admin-group
