---
- hosts: localhost
  connection: local
  tasks:
    - set_fact:
        test: "123456"
    - shell: python -c "x='{{ test }}'; print(x[0:3])"
      register: t2
    - debug:
        msg: "{{ t2.stdout }}"
    - name: last 3 chars
      shell: "echo '{{ test }}' | grep -o ...$"
      register: t3
    - debug:
        msg: "{{ t3.stdout }}"
    - name: except last 3 
      shell: "echo '{{ test }}' | rev | cut -c4- | rev"
      register: t4
    - debug:
        msg: "{{ t4.stdout }}"
