---
- hosts: example
  remote_user: root
  tasks:
    - name: "Pull docker-paas-sig-ci container"
      docker_container:
        name: e2erunner
        image: samvaran/docker-paas-sig-ci
        volumes:
          - /tmp/:/tmp/:z
          - /etc/hosts:/etc/hosts:z
          - /tmp/resolv.conf:/etc/resolv.conf:z
        command: 'tail -f /dev/null'
        detach: yes
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
    - name: "Docker copy ssh keys to docker "
      shell: "docker cp /root/.ssh e2erunner:/root/.ssh"
    - name: "Run command in container"
      docker_exec:
        command: "ansible-playbook -i /tmp/singlenode.inv --private-key /root/.ssh/ex playbooks/openshift/run_e2e_tests.yml -e'containerrun=true'"
        name: e2erunner
      register: e2eoutput
    - name: "Delete the e2e container"
      docker_container:
        name: e2erunner
        state: absent
        keep_volumes: yes
        force_kill: yes
    - name: "Delete e2e file if exists on localhost"
      file:
        state: absent
        path: "/tmp/e2e.log"
      delegate_to: localhost
    - name: "Fetch the file to localhost for display"
      fetch:
        src: /tmp/e2e.log
        dest: /tmp/e2e.log
        flat: yes
      
